databases:
  - name: goldenowlrortest
    databaseName: goldenowlrortest
    user: goldenowlrortest

services:
  - type: web
    name: goldenowlrortest
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: goldenowlrortest
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false